/**
 * @generated by scripts/generate-mc-host-release-manifest.ts. Do not edit.
 * Regenerate: bun scripts/generate-mc-host-release-manifest.ts
 * Drift check: bun scripts/generate-mc-host-release-manifest.ts --check
 *
 * Managed data-root layout segments from the release contract.
 * `retina-local-fs` is a dependency of the plugin packages, so it cannot
 * import their generated contract module; this standalone copy is emitted
 * and drift-checked by the same generator instead.
 */

export const managedLayout = {
    managedSubtree: "cortexkit",
    runtimeDirectory: "run",
    connectionFile: "subc-connection.json",
    storageSubdirectory: "magic-context",
} as const;
