#!/usr/bin/env bun
/**
 *
 * The XML corpus is the editable source of truth.
 * JSON.stringify avoids template-literal escaping when serializing seed blocks.
 *
 * Editing the source corpus requires running `bun run packages/plugin/scripts/build-reference-seeds.ts`.
 */
import { spawnSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const SRC = resolve(here, "../src/hooks/magic-context/reference-seeds.source.xml");
const OUT = resolve(here, "../src/hooks/magic-context/reference-seeds.generated.ts");

const raw = readFileSync(SRC, "utf-8");

const MARKER = /^<!-- seed #\d+ \|[^\n]*-->[ \t]*$/gm;
const markers = [...raw.matchAll(MARKER)];

if (markers.length === 0) {
  throw new Error("build-reference-seeds: no seed markers found in source corpus");
}

interface RawSeed {
  importance: number;
  block: string;
}

const seeds: RawSeed[] = [];
for (let i = 0; i < markers.length; i++) {
  const start = markers[i].index! + markers[i][0].length;
  const end = i + 1 < markers.length ? markers[i + 1].index! : raw.length;
  const block = raw.slice(start, end).trim();
  if (!block.startsWith("<compartment")) {
    throw new Error(
      `build-reference-seeds: seed #${i + 1} does not start with <compartment (got: ${block.slice(0, 40)}...)`,
    );
  }
  const impMatch = block.match(/<compartment[^>]*\bimportance="(\d+)"/);
  if (!impMatch) {
    throw new Error(`build-reference-seeds: seed #${i + 1} has no importance attribute`);
  }
  seeds.push({ importance: Number.parseInt(impMatch[1], 10), block });
}

const header = `// AUTO-GENERATED by scripts/build-reference-seeds.ts from reference-seeds.source.xml
// DO NOT EDIT BY HAND. Regenerate: bun run packages/plugin/scripts/build-reference-seeds.ts
//

export interface ReferenceSeed {
  /** The generator parses importance from the seed's compartment attribute. */
  readonly importance: number;
  /* */
  readonly block: string;
}

export const REFERENCE_SEEDS: ReadonlyArray<ReferenceSeed> = ${JSON.stringify(seeds, null, 2)};
`;

writeFileSync(OUT, header, "utf-8");

const pluginRoot = resolve(here, "..");
const fmt = spawnSync("bunx", ["biome", "check", "--write", OUT], {
  cwd: pluginRoot,
  stdio: "ignore",
});
if (fmt.status !== 0) {
  console.warn(
    `build-reference-seeds: biome format step exited ${fmt.status ?? "null"} (continuing; lint gate will catch any issue)`,
  );
}

console.log(
  `build-reference-seeds: emitted ${seeds.length} seeds (importance ${Math.min(
    ...seeds.map((s) => s.importance),
  )}..${Math.max(...seeds.map((s) => s.importance))}) → ${OUT}`,
);
