#!/usr/bin/env bun
/**
 *
 *
 * `bun run packages/plugin/scripts/build-historian-prompt.ts` regenerates the generated prompt.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const SRC = resolve(here, "../src/hooks/magic-context/historian-prompt.source.md");
const OUT = resolve(here, "../src/hooks/magic-context/historian-prompt.generated.ts");

const raw = readFileSync(SRC, "utf-8").trimEnd();

if (!raw.startsWith("# Historian")) {
  throw new Error("build-historian-prompt: source does not start with '# Historian' header");
}
// The source must state that a small permanent calibration floor is always present.
if (!raw.includes("always present (a small permanent calibration floor)")) {
  throw new Error(
    "build-historian-prompt: source missing the 4-seed-floor reconciliation — refusing to emit a stale 'phases down/disappears' prompt",
  );
}
// The output parser requires `<compartments>`, `<unprocessed_from>`, and `<facts>`.
for (const marker of ["<compartments>", "<unprocessed_from>", "<facts>"]) {
  if (!raw.includes(marker)) {
    throw new Error(`build-historian-prompt: source missing required output marker '${marker}'`);
  }
}

const escaped = raw
  .replace(/\\/g, "\\\\")
  .replace(/`/g, "\\`")
  .replace(/\$\{/g, "\\${");

const out = `// AUTO-GENERATED by scripts/build-historian-prompt.ts from historian-prompt.source.md
// `bun run packages/plugin/scripts/build-historian-prompt.ts` regenerates `historian-prompt.generated.ts`; do not edit that file by hand.
//
// `historian-prompt.source.md` is the editable source; `bun run packages/plugin/scripts/build-historian-prompt.ts` regenerates `historian-prompt.generated.ts`.

export const COMPARTMENT_AGENT_SYSTEM_PROMPT = \`${escaped}\`;
`;

writeFileSync(OUT, out, "utf-8");
console.log(
  `build-historian-prompt: emitted ${raw.length} chars → ${OUT}`,
);
