#!/usr/bin/env bun
/**
 *
 * Run this script as `bun packages/plugin/scripts/export-agent-surface.ts [outPath]`.
 * The script writes to `.cortexkit/alfonso/agent-surface-export.md` when `outPath` is omitted.
 */
import { createHash } from "node:crypto";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import Tokenizer from "ai-tokenizer";
import * as claudeEncoding from "ai-tokenizer/encoding/claude";
import { buildMagicContextSection } from "../src/agents/magic-context-prompt";
import { normalizeToolArgSchemas } from "../src/plugin/normalize-tool-arg-schemas";
import { createCtxExpandTools } from "../src/tools/ctx-expand/tools";
import { createCtxMemoryTools } from "../src/tools/ctx-memory/tools";
import { createCtxNoteTools } from "../src/tools/ctx-note/tools";
import { createCtxReduceTools } from "../src/tools/ctx-reduce/tools";
import { createCtxSearchTools } from "../src/tools/ctx-search/tools";

const tokenizer = new Tokenizer(claudeEncoding);
const t = (s: string) => tokenizer.count(s);

const out: string[] = [];
out.push("# Magic Context agent-facing surface (exported from source)");
out.push("");
out.push(`Generated by \`packages/plugin/scripts/export-agent-surface.ts\` at ${new Date().toISOString().slice(0, 10)}.`);
out.push("Token counts are Claude BPE estimates on the raw text.");
out.push("");

const variants: [string, string][] = [
    [
        "PRIMARY full (reduce=on, memory=on, dreamer=on, temporal=on)",
        buildMagicContextSection(null, 20, true, true, true, false, false, undefined, true),
    ],
    [
        "PRIMARY memory-off (reduce=on, memory=off)",
        buildMagicContextSection(null, 20, true, true, true, false, false, undefined, false),
    ],
    [
        "PRIMARY reduce-off (reduce=off, memory=on)",
        buildMagicContextSection(null, 20, false, true, true, false, false, undefined, true),
    ],
    ["SUBAGENT minimal", buildMagicContextSection(null, 20, true, false, false, false, true)],
];
out.push("## 1. System-prompt guidance section");
out.push("");
for (const [label, text] of variants) {
    out.push(`### ${label} — ${text.length} chars, ~${t(text)} tokens`);
    out.push("");
    out.push("```markdown");
    out.push(text);
    out.push("```");
    out.push("");
}

// The throwing proxy makes the export fail if a `create*Tools` factory invokes a dependency during construction.
const stubDeps = new Proxy(
    {},
    {
        get: (_target, prop) => {
            if (prop === "then") return undefined;
            return () => {
                throw new Error(`stub dep called at tool creation: ${String(prop)}`);
            };
        },
    },
    // biome-ignore lint/suspicious/noExplicitAny: The proxy stub has no concrete dependency type.
) as any;

const definitions = {
    ...createCtxReduceTools(stubDeps),
    ...createCtxExpandTools(stubDeps),
    ...createCtxNoteTools(stubDeps),
    ...createCtxMemoryTools(stubDeps),
    ...createCtxSearchTools(stubDeps),
};

out.push("## 2. Tool surface (description + parameters as serialized to the provider)");
out.push("");
for (const [name, definition] of Object.entries(definitions)) {
    normalizeToolArgSchemas(definition);
    const params: Record<string, unknown> = {};
    for (const [param, schema] of Object.entries(definition.args)) {
        const s = schema as { _zod?: { toJSONSchema?: () => unknown } };
        params[param] = s._zod?.toJSONSchema ? s._zod.toJSONSchema() : "<no toJSONSchema>";
    }
    const serialized = JSON.stringify(params, null, 2);
    const description = definition.description ?? "";
    out.push(
        `### ${name} — description ~${t(description)} tokens, params ~${t(JSON.stringify(params))} tokens (total ~${t(description) + t(JSON.stringify(params))})`,
    );
    out.push("");
    out.push("**Description:**");
    out.push("");
    out.push("```");
    out.push(description);
    out.push("```");
    out.push("");
    out.push("**Parameters (JSON Schema per parameter, as serialized to the provider):**");
    out.push("");
    out.push("```json");
    out.push(serialized);
    out.push("```");
    out.push("");
}

out.push("## 3. System-prompt hash baseline");
out.push("");
out.push(
    'The hash handler persists the MD5 of `output.system.join("\\\\n")`. The values below use each captured guidance section as the complete system array, which is the deterministic no-host-prefix baseline for later compatibility tests. The guidance bytes above are the source bytes; this table records the hash bytes that must remain unchanged when the default prompt surface is selected.',
);
out.push("");
out.push("| Variant | Guidance bytes | MD5 system-prompt hash |");
out.push("|---|---:|---|");
for (const [label, text] of variants) {
    const shortLabel = label.split(" (")[0];
    const bytes = Buffer.byteLength(text, "utf8");
    const md5 = createHash("md5").update(text).digest("hex");
    out.push(`| ${shortLabel} | ${bytes} | \`${md5}\` |`);
}
out.push("");
out.push(
    'The OpenCode and Pi runtime compatibility tests consume this snapshot for omitted `prompt_surface` and explicit `{ default: "full" }`: both assert guidance, registered tool descriptions, tool IDs, and hashes; OpenCode also asserts these parameter schemas directly, while Pi asserts its TypeBox-owned schemas stay byte-identical across both config forms.',
);
out.push("");

const outPath = resolve(process.argv[2] ?? "../../.cortexkit/alfonso/agent-surface-export.md");
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, out.join("\n"));
console.log(`written: ${outPath}`);
