// biome-ignore-all format: generated canonical release data
// Generated by scripts/qualify-mc-host-production-inputs.ts. Do not edit.
export const qualifiedHarnessClosures = {
  "harnesses": {
    "opencode": {
      "anchors": {
        "runtime": {
          "from": "executable",
          "source_path": "opencode.exe"
        }
      },
      "manifest_sha256": "e7e86cd1e1e639fb60aed6dfc3c33cd04244f767f6681a13bf26c90429279f2d",
      "platforms": [
        "linux-x64-gnu"
      ],
      "source_roots": [
        "runtime"
      ]
    },
    "pi": {
      "anchors": {
        "pi-install": {
          "from": "entrypoint",
          "source_path": "node_modules/@earendil-works/pi-coding-agent/dist/cli.js"
        },
        "runtime": {
          "from": "interpreter",
          "source_path": "node"
        }
      },
      "manifest_sha256": "cc87481ce798bd84b9cd0d1dd809bc4c72cea9435303705362a3b2be493674e6",
      "platforms": [
        "linux-x64-gnu"
      ],
      "source_roots": [
        "pi-install",
        "runtime"
      ]
    }
  },
  "schema": "magic-context.mc-host-harness-closure/v1"
} as const;
