#!/usr/bin/env sh
set -eu

root=$(CDPATH= cd -- "$(dirname "$0")/.." && pwd)
parent=$(dirname "$root")
manifest="$root/Cargo.toml"
marker="# generated by scripts/provision-rust-ci-stubs.sh"

# A stub must satisfy its consumer's version requirement.
# Cargo resolution fails before target build.
# Reading the requirement keeps a stub in step with a bump to the manifest.
requirement() {
    name=$1
    line=$(grep -m1 "^$name = " "$manifest" || true)
    version=$(printf '%s\n' "$line" | sed -n 's/.*version = "\([^"]*\)".*/\1/p')
    if [ -z "$version" ]; then
        echo "provision-rust-ci-stubs: no version requirement for $name in $manifest" >&2
        exit 1
    fi
    printf '%s\n' "$version"
}

is_legacy_stub() {
  grep -q '^version = "0.0.0"$' "$1/Cargo.toml" \
    && [ "$(cat "$1/src/lib.rs" 2>/dev/null)" = '#![allow(dead_code)]' ]
}

create_stub() {
  path=$1
  name=$2
  version=$3
  file="$path/Cargo.toml"
  if [ -f "$file" ]; then
    # A real sibling checkout is left alone; only a stub this script wrote is refreshed,
    # so a stale version from an earlier run cannot outlive a bump to the manifest.
    # Stubs written before the marker existed are recognised by their shape instead:
    # a 0.0.0 version and the one-line library body, which no real sibling has.
    if ! grep -qF "$marker" "$file" && ! is_legacy_stub "$path"; then
      return
    fi
    if grep -q "^version = \"$version\"\$" "$file"; then
      return
    fi
  fi
  mkdir -p "$path/src"
  cat >"$file" <<EOF
$marker
[package]
name = "$name"
version = "$version"
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"
EOF
  printf '%s\n' '#![allow(dead_code)]' >"$path/src/lib.rs"
}

for name in cortexkit-cache-core cortexkit-store cortexkit-store-types cortexkit-lease; do
  create_stub "$parent/commons/crates/$name" "$name" "$(requirement "$name")"
done

# No workspace manifest declares a `../subconscious` path dependency, so these
# stubs carry no requirement to satisfy.
create_stub "$parent/subconscious/crates/subc-protocol" subc-protocol 0.0.0
create_stub "$parent/subconscious/crates/subc-control" subc-control 0.0.0
create_stub "$parent/subconscious/crates/subc-transport" subc-transport 0.0.0
create_stub "$parent/subconscious/crates/subc-client-rs" subc-client-rs 0.0.0
create_stub "$parent/subconscious/crates/subc-core" subc-core 0.0.0
