export {
    buildCompartmentBlock,
    escapeXmlAttr,
    escapeXmlContent,
    getCompartments,
    getSessionFacts,
    replaceAllCompartmentState,
    replaceAllCompartmentStateAndBumpDepth,
    type SessionFact,
} from "./compartment-storage";
export {
    clearCompressionDepth,
    getAverageCompressionDepth,
    getMaxCompressionDepth,
    incrementCompressionDepth,
} from "./compression-depth-storage";
export {
    AUTHORITY_DOMAINS,
    type AuthorityDomain,
    type AuthorityManagedMarker,
    type AuthorityModuleClient,
    type AuthorityState,
    type AuthorityStatus,
    applyMirrorPage,
    type ChangefeedPage,
    type ChangefeedRow,
    ensureContextStoreUuid,
    getAuthorityManagedMarker,
    getContextStoreUuid,
    getMirrorCursor,
    installAuthorityManagedMarker,
    listAuthorityManagedMarkers,
    type PrepareAuthorityArgs,
    prepareAuthority,
    reconcileAuthorityMarker,
    removeAuthorityManagedMarker,
} from "./context-authority";
export {
    clearIndexedMessages,
    deleteIndexedMessage,
} from "./message-index";
export {
    computeProjectDocsHash,
    readProjectDocsCanonical,
} from "./project-docs-hash";
export {
    normalizeStoredProjectPath,
    ProjectIdentityError,
    type ProjectIdentityErrorClass,
    resolveProjectIdentity,
    resolveProjectIdentityStrict,
    storedPathBelongsToIdentity,
} from "./project-identity";
export {
    type CloneCompartmentRow,
    type CloneSessionStateFilter,
    type CloneTagRow,
    type CopySessionStateForCloneResult,
    copySessionStateForClone,
} from "./storage-clone";
export {
    applySqliteTuningPragmas,
    type ContextDatabase,
    closeDatabase,
    FORK_MIGRATION_VERSION_FLOOR,
    getDatabasePath,
    getDatabasePersistenceError,
    getFormatRefusal,
    getPersistedSchemaVersion,
    isDatabasePersisted,
    LATEST_SUPPORTED_VERSION,
    type OpenDatabaseOptions,
    openDatabase,
    runSqliteOptimize,
    setSqlitePragmaConfig,
} from "./storage-db";
export {
    type EmbeddingMeasurementInput,
    type EmbeddingMeasurementRow,
    listEmbeddingMeasurements,
    normalizedQueryHash,
    recordEmbeddingMeasurement,
} from "./storage-embedding-measurements";
export {
    deleteIdentityRekeyMap,
    getIdentityRekeyMap,
    type IdentityRekeyMapRow,
    listIdentityRekeyMaps,
    upsertIdentityRekeyMap,
} from "./storage-identity-rekey-map";
export {
    clearM0MutationsForSession,
    deleteM0Mutation,
    getM0Mutation,
    getM0MutationsAfterId,
    getM0MutationsBySession,
    getMaxM0MutationId,
    type M0MutationLogRow,
    type M0MutationType,
    queueM0Mutation,
    queueM0Mutation as appendM0Mutation,
} from "./storage-m0-mutation-log";
export * from "./storage-meta";
export { bumpSessionFactsVersion } from "./storage-meta-shared";
export {
    addNote,
    type ConditionCompileStatus,
    deleteNote,
    dismissNote,
    getNotes,
    getPendingSmartNotes,
    getReadySmartNotes,
    getSessionNotes,
    getSmartNotes,
    markNoteChecked,
    markNoteReady,
    type Note,
    type NoteStatus,
    type NoteType,
    replaceAllSessionNotes,
    type UpdateNoteOptions,
    updateNote,
} from "./storage-notes";
export {
    clearPendingOps,
    getPendingOps,
    queuePendingOp,
    removePendingOp,
} from "./storage-ops";
export * from "./storage-primers";
export {
    bumpProjectMemoryEpoch,
    bumpProjectUserProfileVersion,
    deleteProjectState,
    ensureProjectState,
    GLOBAL_USER_PROFILE_PROJECT_PATH,
    getProjectState,
    type ProjectStateRow,
    setProjectState,
} from "./storage-project-state";
export {
    getSourceContents,
    replaceSourceContent,
    saveSourceContent,
} from "./storage-source";
export {
    getSubagentInvocations,
    getSubagentTotalsBySubagent,
    recordSubagentInvocation,
    type SubagentInvocationInput,
    type SubagentInvocationRow,
    type SubagentKind,
    type SubagentTotals,
} from "./storage-subagent-invocations";
export {
    type ActiveTagTokenAggregate,
    AGE_RECLAIM_MIN_TOKENS,
    type AgeReclaimToolTag,
    adoptFallbackTagMessageId,
    adoptPiFallbackMessageTag,
    adoptPiFallbackToolOwnerTag,
    deleteTagsByMessageId,
    deriveTagLoadFloor,
    findAdoptableFallbackTags,
    findPiFallbackToolOwnerTags,
    getActiveTagsBySession,
    getActiveTagTokenAggregate,
    getActiveTagTokenTotalsByMessage,
    getActiveToolTagsForAgeReclaim,
    getAllStatusTagTokenTotalsFlat,
    getDroppedTagsByNumbers,
    getMaxDroppedTagNumber,
    getMaxTagNumberBySession,
    getMinMessageTagNumberForRawId,
    getOldestActiveUnprotectedToolTags,
    getPersistedToolTagAccounting,
    getTagById,
    getTagsByNumbers,
    getTagsBySession,
    getTagsForPendingOperations,
    getTopNBySize,
    getTriggerTagTokenUpperBound,
    hasPiFallbackMessageTags,
    hasPiFallbackToolOwnerTags,
    insertTag,
    type MessageTokenTotal,
    type ToolReclaimHintTag,
    updateCavemanDepth,
    updateTagDropMode,
    updateTagMessageId,
    updateTagStatus,
} from "./storage-tags";
export {
    clearV22BackfillFailures,
    deleteV22BackfillFailure,
    getV22BackfillFailure,
    listV22BackfillFailures,
    recordV22BackfillFailure,
    type V22BackfillErrorClass,
    type V22BackfillFailureRow,
} from "./storage-v22-backfill-failures";
export {
    bumpEpochsForWorkspaceMembers,
    computeWorkspaceEpochFingerprint,
    type ExpandedWorkspaceIdentitySet,
    expandWorkspaceIdentitySet,
    expandWorkspaceIdentitySetWithAliases,
    resolveStoredPathWorkspaceIdentity,
    resolveWorkspaceIdentitySet,
    sourceNameForMemory,
    type WorkspaceIdentitySet,
} from "./workspaces";
