export const CTX_REDUCE_LIGHT_DESCRIPTION = `For ctx_reduce users, mark spent §N§ outputs discardable; release is QUEUED, not immediate, so content stays visible until space is needed. Newest tags stay protected until they age out. Released content becomes a placeholder; recover it only by rerunning the source or recovery tool, so mark only genuinely finished material. Mark analyzed, redundant, persisted, or merely confirmatory outputs; keep user messages, unresolved errors, unextracted evidence, and exact wording. NEVER blanket-mark a large range: review every tag first.`;

export const CTX_EXPAND_LIGHT_DESCRIPTION = `For ctx_expand users, recover compacted conversation by passing a session-history heading's inclusive start/end ordinals. Results are raw [N] U:/A: transcript capped near 15K tokens; oversized ranges return the head and a continuation. Use verbose=true to list each message ordinal, part previews, and tool-output sizes; use message=N for one complete stored message and its tool exchanges. NEVER expand ranges after the last compartment because that live tail is already visible.`;

export const CTX_NOTE_LIGHT_DESCRIPTION = `For ctx_note users, write saves, read lists, update changes, and dismiss retires future session notes; surface_condition creates a smart note. For smart notes, NEVER use a condition tied to this conversation or an unobservable future action because the background checker can inspect only external GitHub, disk, git, or web signals.`;

export const CTX_MEMORY_LIGHT_DESCRIPTION = `For ctx_memory users, create one durable project claim with category and content; revise, archive, restore, or merge claims by opaque public ID plus the current mutation token, or get up to twenty public IDs. Stale tokens make no change. list remains dreamer-only, so primary agents must NEVER assume bulk-list access.`;

export const CTX_SEARCH_LIGHT_DESCRIPTION = `For ctx_search users, retrieve compacted messages, commits, and notes. Broad project-memory retrieval is disabled until the claim retrieval projection is active; exact public claim or revision locators resolve directly. Message hits continue through ctx_expand.`;
